// SHERLOCK INVESTIGATION DATA
// This file is auto-generated by the Sherlock Research skill.
// Replace this sample data with actual investigation findings.

const INVESTIGATION_DATA = {
  "id": "sample-investigation",
  "title": "Sample Investigation — Acme Corp",
  "target": "Acme Corp",
  "created": "2026-03-03T01:00:00Z",
  "updated": "2026-03-03T01:15:00Z",
  "config": {
    "maxRounds": 5,
    "completedRounds": 2,
    "activeDomains": ["organizations", "people", "financial", "technology", "market"],
    "hypotheses": ["Acme Corp is preparing for an IPO"]
  },
  "graph": {
    "nodes": [
      {"id": "acme-corp", "label": "Acme Corp", "type": "org", "domain": "organizations", "confidence": 95, "round_discovered": 1, "sources": ["https://example.com/acme"], "metadata": {}},
      {"id": "jane-doe", "label": "Jane Doe", "type": "person", "domain": "people", "confidence": 88, "round_discovered": 1, "sources": ["https://linkedin.com/in/janedoe"], "metadata": {}},
      {"id": "john-smith", "label": "John Smith", "type": "person", "domain": "people", "confidence": 82, "round_discovered": 1, "sources": ["https://linkedin.com/in/johnsmith"], "metadata": {}},
      {"id": "series-c", "label": "Series C — $120M", "type": "event", "domain": "financial", "confidence": 92, "round_discovered": 1, "sources": ["https://crunchbase.com/acme"], "metadata": {}},
      {"id": "widget-platform", "label": "Widget Platform v3", "type": "tech", "domain": "technology", "confidence": 75, "round_discovered": 1, "sources": ["https://acme.com/platform"], "metadata": {}},
      {"id": "competitor-a", "label": "Competitor Alpha", "type": "org", "domain": "market", "confidence": 70, "round_discovered": 1, "sources": ["https://example.com/alpha"], "metadata": {}},
      {"id": "competitor-b", "label": "Competitor Beta", "type": "org", "domain": "market", "confidence": 65, "round_discovered": 2, "sources": ["https://example.com/beta"], "metadata": {}},
      {"id": "patent-1", "label": "US Patent 2025/0412", "type": "claim", "domain": "technology", "confidence": 95, "round_discovered": 2, "sources": ["https://patents.google.com/patent/US20250412"], "metadata": {}},
      {"id": "vc-firm", "label": "VC Partners LLP", "type": "org", "domain": "financial", "confidence": 85, "round_discovered": 1, "sources": ["https://example.com/vcpartners"], "metadata": {}},
      {"id": "board-member", "label": "Sarah Chen", "type": "person", "domain": "people", "confidence": 78, "round_discovered": 2, "sources": ["https://linkedin.com/in/sarahchen"], "metadata": {}},
      {"id": "acquisition", "label": "Acquired DataTools Inc", "type": "event", "domain": "organizations", "confidence": 90, "round_discovered": 2, "sources": ["https://techcrunch.com/acme-datatools"], "metadata": {}},
      {"id": "market-share", "label": "Est. 12% Market Share", "type": "claim", "domain": "market", "confidence": 55, "round_discovered": 2, "sources": ["https://analyst-report.com/widgets"], "metadata": {}}
    ],
    "edges": [
      {"source": "jane-doe", "target": "acme-corp", "relationship": "CEO", "confidence": 95, "sources": ["https://acme.com/team"], "round_discovered": 1},
      {"source": "john-smith", "target": "acme-corp", "relationship": "CTO", "confidence": 90, "sources": ["https://acme.com/team"], "round_discovered": 1},
      {"source": "series-c", "target": "acme-corp", "relationship": "funded", "confidence": 92, "sources": ["https://crunchbase.com/acme"], "round_discovered": 1},
      {"source": "vc-firm", "target": "series-c", "relationship": "lead_investor", "confidence": 85, "sources": ["https://crunchbase.com/acme"], "round_discovered": 1},
      {"source": "acme-corp", "target": "widget-platform", "relationship": "develops", "confidence": 88, "sources": ["https://acme.com/platform"], "round_discovered": 1},
      {"source": "acme-corp", "target": "competitor-a", "relationship": "competes_with", "confidence": 75, "sources": ["https://analyst-report.com"], "round_discovered": 1},
      {"source": "acme-corp", "target": "competitor-b", "relationship": "competes_with", "confidence": 60, "sources": ["https://analyst-report.com"], "round_discovered": 2},
      {"source": "john-smith", "target": "patent-1", "relationship": "authored", "confidence": 95, "sources": ["https://patents.google.com"], "round_discovered": 2},
      {"source": "board-member", "target": "acme-corp", "relationship": "board_member", "confidence": 78, "sources": ["https://sec.gov/proxy"], "round_discovered": 2},
      {"source": "board-member", "target": "vc-firm", "relationship": "partner_at", "confidence": 80, "sources": ["https://vcpartners.com/team"], "round_discovered": 2},
      {"source": "acme-corp", "target": "acquisition", "relationship": "acquired", "confidence": 90, "sources": ["https://techcrunch.com"], "round_discovered": 2},
      {"source": "acme-corp", "target": "market-share", "relationship": "holds", "confidence": 55, "sources": ["https://analyst-report.com"], "round_discovered": 2},
      {"source": "widget-platform", "target": "patent-1", "relationship": "protected_by", "confidence": 80, "sources": ["https://patents.google.com"], "round_discovered": 2}
    ]
  },
  "deductions": [
    {
      "id": "ded-1",
      "observation": "Acme Corp raised $120M Series C and acquired DataTools Inc within 6 months",
      "inference": "Acme Corp is aggressively positioning for market dominance or IPO preparation — the combination of large fundraise + strategic acquisition suggests expansion ahead of a liquidity event",
      "confidence": 78,
      "supporting": [
        {"claim": "CEO Jane Doe mentioned 'next chapter' at Web Summit 2025", "source": "https://websummit.com/talks/acme"},
        {"claim": "Series C was led by VC Partners LLP, known for pre-IPO investments", "source": "https://crunchbase.com/acme"},
        {"claim": "DataTools acquisition expands their enterprise data pipeline offering", "source": "https://techcrunch.com/acme-datatools"}
      ],
      "contradicting": [
        {"claim": "CFO stated 'no plans for public offering in 2026' in press interview", "source": "https://bloomberg.com/acme-cfo"},
        {"claim": "Company still burning $8M/month according to leaked financials", "source": "https://theinformation.com/acme-burn"}
      ],
      "synthesis": "The IPO hypothesis is probable but not confirmed. Financial indicators point toward preparation, but management denials and high burn rate suggest 2027 is more likely than 2026. Monitor for S-1 filing signals and additional board appointments.",
      "round": 2,
      "domain": "financial"
    },
    {
      "id": "ded-2",
      "observation": "CTO John Smith filed a patent for 'distributed widget processing' (US Patent 2025/0412)",
      "inference": "Acme Corp is building proprietary distributed computing technology, potentially pivoting from monolithic to distributed architecture",
      "confidence": 72,
      "supporting": [
        {"claim": "Widget Platform v3 release notes mention 'distributed processing mode'", "source": "https://acme.com/changelog"},
        {"claim": "3 job postings for distributed systems engineers in the last month", "source": "https://acme.com/careers"}
      ],
      "contradicting": [
        {"claim": "Patent may be defensive rather than product-focused", "source": ""}
      ],
      "synthesis": "The patent filing aligns with product direction but could be defensive IP strategy. The hiring pattern supports active development rather than purely defensive filing.",
      "round": 2,
      "domain": "technology"
    }
  ],
  "roundHistory": [
    {
      "round": 1,
      "timestamp": "2026-03-03T01:05:00Z",
      "queriesExecuted": 8,
      "newNodes": 6,
      "newEdges": 6,
      "avgConfidence": 84,
      "summary": "Initial sweep identified Acme Corp leadership (CEO Jane Doe, CTO John Smith), Series C funding ($120M led by VC Partners), core product (Widget Platform v3), and primary competitor (Competitor Alpha).",
      "expansionStrategy": "broad_sweep"
    },
    {
      "round": 2,
      "timestamp": "2026-03-03T01:12:00Z",
      "queriesExecuted": 12,
      "newNodes": 6,
      "newEdges": 7,
      "avgConfidence": 74,
      "summary": "Deepened financial and technology domains. Discovered DataTools acquisition, Sarah Chen board appointment (links VC Partners to board), CTO patent filing, second competitor (Beta), and initial market share estimate. IPO hypothesis strengthened but not confirmed.",
      "expansionStrategy": "leaf_expansion"
    }
  ],
  "gaps": [
    {
      "domain": "financial",
      "description": "No 2025 revenue figures or growth rate data found. Needed to validate IPO readiness hypothesis.",
      "suggestedQueries": ["Acme Corp 2025 revenue", "Acme Corp ARR", "Acme Corp financial performance"],
      "priority": "high"
    },
    {
      "domain": "people",
      "description": "No data on recent executive hires beyond board level. CFO identity unknown.",
      "suggestedQueries": ["Acme Corp CFO", "Acme Corp executive team 2026", "Acme Corp leadership changes"],
      "priority": "medium"
    },
    {
      "domain": "market",
      "description": "Market share estimate (12%) from single analyst report. Needs corroboration.",
      "suggestedQueries": ["widget platform market share 2025", "Acme Corp vs Competitor Alpha market"],
      "priority": "medium"
    }
  ]
};
